---
title:               Coder On Code
tagline:             "Node.js, Ruby, Magento"
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "admin" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "coder2012$" %>
name:                Your name
twitter:             allanmacgregor
github:              amacgregor
linkedin:	     allanmacgregor
email:               info@coderoncode.com
google_analytics_id: UA-28450068-1
