---
title:               CoderOnCode
tagline:             Ruby, Vim, Programming and Technologie
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "amacgregor" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "coderoncoder789632145." %>
name:                Allan MacGregor
twitter:             allanmacgregor
github:              amacgregor
email:               amacgregor@allanmacgregor.com
google_analytics_id: UA-28450068-1
