---
title:               Coder On Code
tagline:             "Node.js, Ruby, Magento"
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Your name
twitter:             amacgregor
github:              amacgregor
linkedin:			 allanmacgregor
email:               info@coderoncode.com
google_analytics_id: YOUR_GA_ID